# Generated by Django 5.2.8 on 2025-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_reservation_date_booking_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='menu_items/default.jpg', upload_to='menu_items/'),
        ),
    ]
