# Generated by Django 5.2.8 on 2025-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
