# Generated by Django 5.2.8 on 2025-11-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image_filename',
        ),
    ]
